In [ ]:
import numpy as np
import plotly.graph_objs as go


In [ ]:
from pystochastic.processes.continuous import BrownianMotion as TestType
from stochastic.continuous import BrownianMotion as StochasticTestType


In [ ]:
seed = 1234567890
n = 10
t = 1
drift = 0.2
scale = 1.3

rng = np.random.default_rng(seed)
np.random.seed(seed)


In [ ]:
x = TestType(drift=drift, scale=scale, t=t, rng=rng)
xs = x.sample(n=n)

y = StochasticTestType(drift=drift, scale=scale, t=t)
ys = y.sample(n=n)


In [ ]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        y=xs,
        mode="lines",
        name="Current",
    )
)

fig.add_trace(
    go.Scatter(
        y=ys,
        mode="lines",
        name="Original",
    )
)


fig.update_layout(
    title="Samples",
    xaxis_title="Sample Index",
    yaxis_title="Amplitude",
)

fig.show()


In [ ]:
display(xs, ys)


array([ 0.        , -0.81835942, -0.79085671, -1.07202826, -0.71934958,
       -0.4545992 , -0.32214094, -0.51529092, -0.26270316, -0.34387727,
       -0.3224625 ])

array([ 0.        , -0.81835942, -0.79085671, -1.07202826, -0.71934958,
       -0.4545992 , -0.32214094, -0.51529092, -0.26270316, -0.34387727,
       -0.3224625 ])

In [ ]:
seed = 1234567890
n = 10
t = 1
drift = 0.0
scale = 1.0

rng = np.random.default_rng(seed)
np.random.seed(seed)


In [ ]:
x = TestType(drift=drift, scale=scale, t=t, rng=rng)
xs = x.sample(n=n)

y = StochasticTestType(drift=drift, scale=scale, t=t)
ys = y.sample(n=n)


In [ ]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        y=xs,
        mode="lines",
        name="Current",
    )
)

fig.add_trace(
    go.Scatter(
        y=ys,
        mode="lines",
        name="Original",
    )
)


fig.update_layout(
    title="Samples",
    xaxis_title="Sample Index",
    yaxis_title="Amplitude",
)

fig.show()


In [ ]:
display(xs, ys)


array([ 0.        , -0.64489186, -0.63912054, -0.87079097, -0.61488429,
       -0.42661477, -0.34010841, -0.50406994, -0.32515628, -0.40298251,
       -0.40189423])

array([ 0.        , -0.64489186, -0.63912054, -0.87079097, -0.61488429,
       -0.42661477, -0.34010841, -0.50406994, -0.32515628, -0.40298251,
       -0.40189423])