In [ ]:
import numpy as np
import plotly.graph_objs as go


In [ ]:
from pystochastic.processes.continuous import BrownianBridge as TestType
from stochastic.continuous import BrownianBridge as StochasticTestType


In [ ]:
seed = 1234567890
n = 10
t = 1
b = 0.2

rng = np.random.default_rng(seed)
np.random.seed(seed)


In [ ]:
x = TestType(b=b, t=t, rng=rng)
xs = x.sample(n=n)

y = StochasticTestType(b=b, t=t)
ys = y.sample(n=n)


In [ ]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        y=xs,
        mode="lines",
        name="Current",
    )
)

fig.add_trace(
    go.Scatter(
        y=ys,
        mode="lines",
        name="Original",
    )
)


fig.update_layout(
    title="Samples",
    xaxis_title="Sample Index",
    yaxis_title="Amplitude",
)

fig.show()


In [ ]:
display(xs, ys)


array([ 0.        , -0.58470244, -0.5187417 , -0.6902227 , -0.3741266 ,
       -0.12566765,  0.02102813, -0.08274397,  0.15635911,  0.1387223 ,
        0.2       ])

array([ 0.        , -0.58470244, -0.5187417 , -0.6902227 , -0.3741266 ,
       -0.12566765,  0.02102813, -0.08274397,  0.15635911,  0.1387223 ,
        0.2       ])

In [ ]:
seed = 1234567890
n = 10
t = 1
b = 0.0

rng = np.random.default_rng(seed)
np.random.seed(seed)


In [ ]:
x = TestType(b=b, t=t, rng=rng)
xs = x.sample(n=n)

y = StochasticTestType(b=b, t=t)
ys = y.sample(n=n)


In [ ]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        y=xs,
        mode="lines",
        name="Current",
    )
)

fig.add_trace(
    go.Scatter(
        y=ys,
        mode="lines",
        name="Original",
    )
)


fig.update_layout(
    title="Samples",
    xaxis_title="Sample Index",
    yaxis_title="Amplitude",
)

fig.show()


In [ ]:
display(xs, ys)


array([ 0.        , -0.60470244, -0.5587417 , -0.7502227 , -0.4541266 ,
       -0.22566765, -0.09897187, -0.22274397, -0.00364089, -0.0412777 ,
        0.        ])

array([ 0.        , -0.60470244, -0.5587417 , -0.7502227 , -0.4541266 ,
       -0.22566765, -0.09897187, -0.22274397, -0.00364089, -0.0412777 ,
        0.        ])