In [ ]:
import numpy as np
import plotly.graph_objs as go


In [ ]:
from pystochastic.processes.continuous import VarianceGammaProcess as TestType
from stochastic.continuous import VarianceGammaProcess as StochasticTestType


In [ ]:
seed = 1234567890
n = 10
t = 1
drift = 0.2
variance = 0.5
scale = 1.3

rng = np.random.default_rng(seed)
np.random.seed(seed)


In [ ]:
x = TestType(drift=drift, variance=variance, scale=scale, t=t, rng=rng)
xs = x.sample(n=n)

y = StochasticTestType(drift=drift, variance=variance, scale=scale, t=t)
ys = y.sample(n=n)


In [ ]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        y=xs,
        mode="lines",
        name="Current",
    )
)

fig.add_trace(
    go.Scatter(
        y=ys,
        mode="lines",
        name="Original",
    )
)


fig.update_layout(
    title="Samples",
    xaxis_title="Sample Index",
    yaxis_title="Amplitude",
)

fig.show()


In [ ]:
display(xs, ys)


array([ 0.        , -0.02950298, -0.04686612, -0.00477412, -0.06179967,
       -0.10590249, -0.13582478, -0.25132632, -0.24706702, -0.34024965,
       -0.30786848])

array([ 0.        , -0.16948641, -0.10030517, -0.12845981, -0.11965339,
       -0.07795688, -0.06882281, -0.08348159, -0.08345431, -0.0835958 ,
       -0.08349826])

In [ ]:
seed = 1234567890
n = 10
t = 1
drift = 0.0
variance = 0.5
scale = 1.0

rng = np.random.default_rng(seed)
np.random.seed(seed)


In [ ]:
x = TestType(drift=drift, variance=variance, scale=scale, t=t, rng=rng)
xs = x.sample_at(n=n)

y = StochasticTestType(drift=drift, variance=variance, scale=scale, t=t)
ys = y.sample(n=n)


In [ ]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        y=xs,
        mode="lines",
        name="Current",
    )
)

fig.add_trace(
    go.Scatter(
        y=ys,
        mode="lines",
        name="Original",
    )
)


fig.update_layout(
    title="Samples",
    xaxis_title="Sample Index",
    yaxis_title="Amplitude",
)

fig.show()


In [ ]:
display(xs, ys)


array([ 0.        , -0.0095009 , -0.03159831, -0.04989379, -0.05412636,
       -0.06448488,  0.27521011,  0.27519587,  0.36347741,  0.36321412,
        0.36321412])

array([ 0.        , -0.05850865, -0.05530968, -0.05995639, -0.05960873,
       -0.05095646, -0.05005951, -0.05185017, -0.05185016, -0.05185047,
       -0.05184969])