In [ ]:
import numpy as np
import plotly.graph_objs as go


In [ ]:
from pystochastic.processes.noise import GaussianNoise as TestType
from stochastic.noise import GaussianNoise as StochasticTestType


In [ ]:
seed = 1234567890
n = 10
t = 1

rng = np.random.default_rng(seed)
np.random.seed(seed)


In [ ]:
x = TestType(t=t, rng=rng)
xs = x.sample(n=n)


y = StochasticTestType(t=t)
ys = y.sample(n=n)


In [ ]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        y=xs,
        mode="lines",
        name="Current",
    )
)

fig.add_trace(
    go.Scatter(
        y=ys,
        mode="lines",
        name="Original",
    )
)


fig.update_layout(
    title="Samples",
    xaxis_title="Sample Index",
    yaxis_title="Amplitude",
)

fig.show()


In [ ]:
display(xs, ys)


array([-0.64489186,  0.00577132, -0.23167042,  0.25590667,  0.18826952,
        0.08650636, -0.16396152,  0.17891366, -0.07782623,  0.00108828])

array([-0.64489186,  0.00577132, -0.23167042,  0.25590667,  0.18826952,
        0.08650636, -0.16396152,  0.17891366, -0.07782623,  0.00108828])

In [ ]:
rng = np.random.default_rng(seed)
np.random.seed(seed)


In [ ]:
times = np.linspace(0, t, n + 1)

x = TestType(t=t, rng=rng)
xs = x.sample_at(times=times)


y = StochasticTestType(t=t)
ys = y.sample_at(times=times)


In [ ]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=times,
        y=xs,
        mode="lines",
        name="Current",
    )
)

fig.add_trace(
    go.Scatter(
        x=times,
        y=ys,
        mode="lines",
        name="Original",
    )
)


fig.update_layout(
    title="Samples",
    xaxis_title="Sample Index",
    yaxis_title="Amplitude",
)

fig.show()


In [ ]:
display(xs, ys)


array([-0.64489186,  0.00577132, -0.23167042,  0.25590667,  0.18826952,
        0.08650636, -0.16396152,  0.17891366, -0.07782623,  0.00108828])

array([-0.64489186,  0.00577132, -0.23167042,  0.25590667,  0.18826952,
        0.08650636, -0.16396152,  0.17891366, -0.07782623,  0.00108828])